### ISSUE TITLE
App is Crashing after few seconds

### ISSUE THREAD

**Issue by imdineshsingh** [deepakgahlot98/NeverEndingService#1]
logs::

2020-11-06 18:44:49.446 18680-18680/com.gahlot.neverendingservice E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gahlot.neverendingservice, PID: 18680
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{334cb5f u0 com.gahlot.neverendingservice/.AutoStartService}
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1760)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by YordanYanakiev** [comment]
I can confirm that.
On older Androids - it works so-so, but in Android 10 it crash right away 2-3 seconds after it starts.
Aside of this there is part which is rather weird, and I am not sure if the service actually working the way it is described..

**Comment by saketmilan98** [comment]
Same issue, did you got any solution?

**Comment by YordanYanakiev** [comment]
Nope. I ditched it. The reason is unclear.

**Comment by jatin-lakhani** [comment]
Any solution ?

**Comment by realyukii** [comment]
👀
